layout_spectrum: 0.5361057613044977
typography_spectrum: 0.17496476718224585
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.6271704675164074
  lightness: 0.864605852868408
  saturation: 0.7934490314219147
  rhythmicContrast: 0.9930186446290463
name: Christian Raharjo
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
